### ISSUE TITLE
CuQuantum import error

### ISSUE THREAD

**Issue by sorewachigauyo** [qiboteam/qibojit#231]
The newer CuQuantum versions (25.9.1 on my machine) has changed their import API (https://github.com/NVIDIA/cuQuantum/blob/main/python/cuquantum/__init__.py) and so this line is now not working https://github.com/qiboteam/qibojit/blob/main/src/qibojit/backends/gpu.py#L584

```
Traceback (most recent call last):
  File "/mnt/scratch/pault/qibo-test.py", line 3, in <module>
    qibo.set_backend("qibojit", platform="cuquantum")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/scratch/envs/qibo-experimental/lib/python3.13/site-packages/qibo/backends/__init__.py", line 220, in set_backend
    _Global.set_backend(backend, **kwargs)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/mnt/scratch/envs/qibo-experimental/lib/python3.13/site-packages/qibo/backends/__init__.py", line 125, in set_backend
    cls._backend = construct_backend(backend, **kwargs)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/mnt/scratch/envs/qibo-experimental/lib/python3.13/site-packages/qibo/backends/__init__.py", line 342, in construct_backend
    raise e
  File "/mnt/scratch/envs/qibo-experimental/lib/python3.13/site-packages/qibo/backends/__init__.py", line 338, in construct_backend
    return getattr(module, "MetaBackend").load(**kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/mnt/scratch/envs/qibo-experimental/lib/python3.13/site-packages/qibojit/backends/__init__.py", line 29, in load
    return CuQuantumBackend()
  File "/mnt/scratch/envs/qibo-experimental/lib/python3.13/site-packages/qibojit/backends/gpu.py", line 584, in __init__
    from cuquantum import custatevec as cusv  # pylint: disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'custatevec' from 'cuquantum' (/mnt/scratch/envs/qibo-experimental/lib/python3.13/site-packages/cuquantum/__init__.py)
```

It seems to work fine with cuquantum-python-cu12==25.6.0
