### PR TITLE
Update cuQuantum version

### LINKED ISSUE #76: Cuquantum fails using the latest release
I believe a new cuquantum-python version was uploaded in [conda-forge](https://anaconda.org/conda-forge/cuquantum-python) yesterday and there are some changes in the API. For example our cuquantum tests both in qibo and qibojit now fail with
```
AttributeError: module 'cuquantum.custatevec' has no attribute 'apply_matrix_buffer_size'
```
I believe this method was renamed to [`apply_matrix_get_workspace_size`](https://docs.nvidia.com/cuda/cuquantum/python/api/custatevec.html#general-matrices) in the latest version. I have not checked in detail if any other changes have been made.

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Closes #76. This PR fixes a few bugs that we had with  [latest](https://docs.nvidia.com/cuda/cuquantum/python/release_notes.html#cuquantum-python-v22-03-0) version of cuquatum.
Now, both qibo and qibojit tests are passing on dom. @stavros11 when you have time please check if tests are passing also for you.

### CODE REVIEW

**Review by stavros11 — APPROVED** [review]
Thanks for the fix, I tried the tests in my laptop and the DGX and they pass with the latest version of cuquantum from conda. I get some failures in the DGX which seem to be related to multigpu but I do not think they are because of this PR or cuquantum. I will have a more detailed look.

Regarding this PR, my only comment would be that we should add somewhere in the documentation that this version will work with the latest cuquantum-python (22.03), as it will fail if someone tries to use it with the previous version (before the renaming). We may need to do this in the qibo repo since the documentation is there.

**Comment by andrea-pasquale** [comment]
Thanks for the review.

> Regarding this PR, my only comment would be that we should add somewhere in the documentation that this version will work with the latest cuquantum-python (22.03), as it will fail if someone tries to use it with the previous version (before the renaming). We may need to do this in the qibo repo since the documentation is there.

I totally agree. I'll open an issue here so that we can remember it.

**Review by scarrazza — APPROVED** [review]
